#!/usr/bin/env bash
# Stolen from https://github.com/pote/dotfiles

BLACKLIST=".
..
.git
.osx
"

for file in .*
do
  if [[ $BLACKLIST =~ $file ]]
  then
    echo Ignoring blacklisted file: $file
  else
    echo Creating symlink for: $file in $HOME
    ln -s $PWD/$file $HOME/$file
  fi
done

