#!/usr/bin/env bash
# Stolen from https://github.com/pote/dotfiles

DENYLIST=".
..
.git
.osx
"

for file in .*
do
  if [[ $DENYLIST =~ $file ]]
  then
    echo Ignoring denylisted file: $file
  else
    echo Creating symlink for: $file in $HOME
    ln -sfn "$PWD/$file" "$HOME/$file"
  fi
done

mkdir -p "$HOME/.config"
echo Creating symlink for: ghostty in $HOME/.config
ln -sfn "$PWD/ghostty" "$HOME/.config/ghostty"
