tap "homebrew/cask-fonts"

brew "bat"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "ripgrep"
brew "tmux"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
